#!/usr/bin/env python3
"""Prepare an isolated Windows Swift/Crypto experiment from the current core and tests."""
import argparse
import hashlib
import json
from pathlib import Path
import shutil

ROOT = Path(__file__).resolve().parents[2]
CRYPTO_REVISION = "a9d1d5ab8951ada40cafff8c8e2b551dfde4f390"  # Swift Crypto 5.0.0.


def prepare(output, host_bridge=False):
    output = output.resolve()
    if not output.is_relative_to(ROOT / "tools/windows/results"):
        raise ValueError("experiment must be inside tools/windows/results")
    output.mkdir(parents=True, exist_ok=False)
    files = []
    for folder in ("macos/Sources/LightrayCore", "macos/Tests/LightrayCoreTests"):
        for path in sorted((ROOT / folder).rglob("*")):
            if not path.is_file() or path.suffix not in (".swift", ".json"):
                continue
            target = output / path.relative_to(ROOT)
            target.parent.mkdir(parents=True, exist_ok=True)
            original = path.read_bytes()
            payload = original.replace(b"import CryptoKit", b"import Crypto") if path.suffix == ".swift" else original
            target.write_bytes(payload)
            files.append({"path": path.relative_to(ROOT).as_posix(), "source_sha256": hashlib.sha256(original).hexdigest(), "probe_sha256": hashlib.sha256(payload).hexdigest()})
    vectors = output / "tools/vectors/vectors.json"
    vectors.parent.mkdir(parents=True)
    shutil.copyfile(ROOT / "tools/vectors/vectors.json", vectors)
    shutil.copyfile(ROOT / "tools/windows/src/core_bridge.swift", output / "macos/Sources/LightrayCore/CoreBridge.swift")
    if host_bridge:
        shutil.copyfile(ROOT / "tools/windows/src/host_bridge.swift", output / "macos/Sources/LightrayCore/HostBridge.swift")
        shutil.copyfile(ROOT / "tools/windows/src/host_probe_client.swift", output / "macos/Sources/LightrayCore/HostProbeClient.swift")
        shutil.copyfile(ROOT / "tools/windows/src/host_bridge_tests.swift", output / "macos/Tests/LightrayCoreTests/HostBridgeTests.swift")
    package = '''// swift-tools-version: 6.2
import PackageDescription

let package = Package(
    name: "LightrayCoreProbe",
    platforms: [.macOS(.v14)],
    products: [.library(name: "LightrayCoreProbe", type: .dynamic, targets: ["LightrayCore"])],
    dependencies: [.package(url: "https://github.com/apple/swift-crypto.git", revision: "CRYPTO_REVISION")],
    targets: [
        .target(name: "LightrayCore", dependencies: [.product(name: "Crypto", package: "swift-crypto")]),
        .testTarget(name: "LightrayCoreTests", dependencies: ["LightrayCore", .product(name: "Crypto", package: "swift-crypto")], resources: [.copy("Fixtures")]),
    ]
)
'''.replace("CRYPTO_REVISION", CRYPTO_REVISION)
    (output / "macos/Package.swift").write_text(package)
    shutil.copyfile(ROOT / "tools/windows/reference/swift-core-package.resolved", output / "macos/Package.resolved")
    data = json.loads(vectors.read_text())["protected_datagram"]
    header = ["// Public protocol vectors; generated by prepare-swift-core.py.", "#pragma once", "#include <cstdint>"]
    for name, value in (("key", data["inputs"]["key"]), ("packet", data["outputs"]["datagram"]), ("plaintext", data["inputs"]["chunks"])):
        values = ", ".join(f"0x{byte:02x}" for byte in bytes.fromhex(value))
        header.append(f"constexpr std::uint8_t {name}[] = {{{values}}};")
    number = data["inputs"]["packet_number"]
    number = number if isinstance(number, int) else int(number, 16)
    header.append(f"constexpr std::uint64_t packet_number = {number}ULL;")
    (output / "core_probe_vectors.h").write_text("\n".join(header) + "\n")
    inputs = {}
    for name in ("tools/vectors/vectors.json", "tools/windows/src/core_bridge.swift", "tools/windows/src/core_abi_probe.cpp", "tools/windows/reference/swift-core-package.resolved", "tools/windows/build-swift-core-probe.ps1"):
        inputs[name] = hashlib.sha256((ROOT / name).read_bytes()).hexdigest()
    if host_bridge:
        for name in ("host_bridge.swift", "host_bridge_tests.swift", "host_bridge.h", "host_probe_client.swift", "host_abi_probe.cpp", "nvenc_encoder.hpp", "nvenc_encoder.cpp", "hevc_annexb.hpp", "udp_loopback.hpp"):
            inputs["tools/windows/src/" + name] = hashlib.sha256((ROOT / "tools/windows/src" / name).read_bytes()).hexdigest()
    manifest = {"host_bridge": host_bridge, "minimum_tests": 88 if host_bridge else 80, "crypto_version": "5.0.0", "crypto_revision": CRYPTO_REVISION, "transformation": "Replace import CryptoKit with import Crypto in isolated copies only", "files": files, "other_inputs_sha256": inputs}
    (output / "source-manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    return manifest


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--host-bridge", action="store_true")
    args = parser.parse_args()
    result = prepare(args.output, args.host_bridge)
    print(json.dumps({"status": "prepared", "source_files": len(result["files"]), "crypto_revision": CRYPTO_REVISION}))
